"""Initial migration

Revision ID: 8e9a4626f179
Revises: 
Create Date: 2025-03-11 01:16:31.719417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e9a4626f179'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passengers')
    op.drop_table('tickets')
    with op.batch_alter_table('booking_passenger', schema=None) as batch_op:
        batch_op.alter_column('class_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=mysql.ENUM('Male', 'Female', 'Other'),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('id_proof',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_constraint('fk_train_passenger', type_='foreignkey')
        batch_op.create_foreign_key(None, 'trains', ['train_id'], ['train_id'])

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('train_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('ticket_class',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'Economy'"))
        batch_op.alter_column('pnr',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_index('idx_train_name')
        batch_op.drop_index('idx_travel_date')
        batch_op.drop_constraint('fk_train', type_='foreignkey')
        batch_op.drop_constraint('fk_user', type_='foreignkey')
        batch_op.create_foreign_key(None, 'trains', ['train_id'], ['train_id'])
        batch_op.drop_column('class')

    with op.batch_alter_table('passengers_info', schema=None) as batch_op:
        batch_op.drop_constraint('passengers_info_ibfk_2', type_='foreignkey')
        batch_op.drop_column('booking_id')

    with op.batch_alter_table('trains', schema=None) as batch_op:
        batch_op.drop_index('train_id')

    with op.batch_alter_table('user_accounts', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.create_unique_constraint(None, ['email'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('registered_on',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('registered_on',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('user_accounts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('trains', schema=None) as batch_op:
        batch_op.create_index('train_id', ['train_id'], unique=True)

    with op.batch_alter_table('passengers_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('passengers_info_ibfk_2', 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_user', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_train', 'trains', ['train_id'], ['train_id'], ondelete='CASCADE')
        batch_op.create_index('idx_travel_date', ['travel_date'], unique=False)
        batch_op.create_index('idx_train_name', ['train_name'], unique=False)
        batch_op.alter_column('pnr',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('ticket_class',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("'Economy'"))
        batch_op.alter_column('train_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('booking_passenger', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_train_passenger', 'trains', ['train_id'], ['train_id'], ondelete='CASCADE')
        batch_op.alter_column('id_proof',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.String(length=10),
               type_=mysql.ENUM('Male', 'Female', 'Other'),
               existing_nullable=False)
        batch_op.alter_column('class_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    op.create_table('tickets',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('train_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('departure', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('destination', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('travel_date', sa.DATE(), nullable=True),
    sa.Column('seat_number', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['passengers_info.id'], name='tickets_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('passengers',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gender', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('id_proof', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name='passengers_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
